_target_: diffusion.difo.DiffusionModule
diffusion:
  _target_: diffusion.difo.Diffusion
  timesteps: 1000
  scheduler:
    _target_: diffusion.schedulers.LinearScheduler
    start: 0.0001
    end: 0.02
model:
  _target_: diffusion.unet.Unet
  in_channels: 1
  init_channels: 16
  channels: [128, 128, 256, 512]
  heads: 4
  head_dim: 32


