wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: "${run_name}"
  save_dir: "${paths.log_dir}/${task_name}/"
  offline: False
  log_model: False
  version: ${run_name}
  anonymous: null 
  project: "${task_name}"
  prefix: ""
  group: ""
  tags: []
  job_type: ""
