image_generation:
  _target_: diffusion.callbacks.image_generation.ImageGenerationCallback
  output_dir: ${trainer.default_root_dir}
  predict_samples: ${predict_samples}
  every_n_epochs: null
  verbose: True
