defaults:
  - _self_
  - paths: default
  - hydra: default
  - extras: default
  - logger: none

accelerator: gpu

show: True
samples: 16
batch_size: 16
sample_timesteps: 1000

task_name: null
run_name: null
ckpt_name: last.ckpt
