defaults:
  - _self_
  - paths: default
  - hydra: default
  - extras: default
  - trainer: cpu
  - callbacks: sample

task_name: mnist_diffusion
run_name: icy-horizon-51
ckpt_name: last.ckpt
show: False
predict_samples: 4
batch_size: 4
sample_timesteps: 1000

# To be set with the training job config, necessary to propagate to ImageGeneration callback.
in_channels: null 
dim: null
