# @package _global_
defaults:
  - _self_
  - callbacks: default
  - logger: wandb
  - paths: default
  - extras: default
  - hydra: default

  - trainer: cpu
  - data: mnist
  - diffusion: gaussian_diffusion

  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

in_channels: 1
out_channels: 2
samples: 4
dim: 28
timesteps: 1000

task_name: "sample"
tags: ["dev"]
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null
