# @package _global_
defaults:
  - _self_
  - callbacks: default
  - logger: wandb
  - paths: default
  - extras: default
  - hydra: default

  - trainer: cpu
  - data: mnist
  - diffusion: gaussian_diffusion

  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

in_channels: null
out_channels: null

timesteps: 1000
sample_timesteps: 1000
batch_size: 128

task_name: "cifar_release_1"
run_name: null

tags: ["dev"]
train: True
validate: False

predict_samples: 4

ckpt_name: "last.ckpt"
seed: null
