# @package _global_
defaults:
  - _self_
  - callbacks: default
  - logger: wandb
  - paths: default
  - extras: default
  - hydra: default

  - trainer: cpu
  - data: mnist
  - diffusion: gaussian_diffusion

  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

in_channels: 1
out_channels: 1
dim: 28
timesteps: 1000

task_name: "mnist_diffusion"
project: "diffusion"
group: "mnist"
run_name: null

tags: ["dev"]
train: True
test: True
predict: True

predict_samples: 4

ckpt_name: "last.ckpt"
seed: null
