defaults:
- _self_
- callbacks: default
- logger: wandb
- paths: default
- extras: default
- hydra: default
- trainer: cpu
- data: mnist
- diffusion: gaussian_diffusion
- experiment: null
- hparams_search: null
- optional local: default
- debug: null
in_channels: 1
out_channels: 1
dim: 28
timesteps: 1000
task_name: mnist_diffusion
project: diffusion
group: mnist
run_name: clever-glacier-96
tags:
- dev
train: true
test: true
ckpt_name: last.ckpt
seed: null
