defaults:
  - _self_
  - scheduler: linear
  - mean_strategy: epsilon
  - variance_strategy: fixed_small
  - loss: mse_mean_epsilon_simple
  - sampler: ddpm
  - model: unet

_target_: diffusion.gaussian_diffusion.GaussianDiffusion
timesteps: ${timesteps}
sample_timesteps: ${sample_timesteps}
scheduler: ${scheduler}
mean_strategy: ${mean_strategy}
variance_strategy: ${variance_strategy}
sampler: ${sampler}
loss: ${loss}
model: ${model}
in_channels: ${in_channels}
