defaults:
  - _self_
  - scheduler: linear
  - mean_strategy: epsilon
  - variance_strategy: fixed_small
  - loss: mse_epsilon_simple
  - image_sampler: ddpm
  - timestep_sampler: uniform
  - model: unet

_target_: diffusion.gaussian_diffusion.GaussianDiffusion
timesteps: ${timesteps}
sample_timesteps: ${sample_timesteps}
scheduler: ${scheduler}
mean_strategy: ${mean_strategy}
variance_strategy: ${variance_strategy}
image_sampler: ${image_sampler}
timestep_sampler: ${timestep_sampler}
loss: ${loss}
model: ${model}
optimizer: ${optimizer}
